#!/usr/bin/env bash
#Bash script that change the ip of localhost and facebook

cp /etc/hosts ~/hosts.new
sed -i s/^172.*$/172.0.0.2/ ~/hosts.new
sed -i 's/157\.240\.11\.35/8.8.8.8/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
